import './globals.scss';

export const metadata = {
	title: 'Onara',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body>{children}</body>
		</html>
	);
}
