import type { NextPage } from 'next';
import Head from 'next/head';

import Attention from '@/components/Attention';

import styles from './index.module.scss';

const Features: NextPage = () => {
	return (
		<>
			<Head>
				<title>Features</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.svg" />
			</Head>

			<main className="main">
				<div className={styles.page_content}>
					<div className={styles.masthead}>
						<span>Features</span>
						<h1>The new standard for modern software development</h1>
						<p>
							With its meticulous design, breathtaking speed and opinionated yet
							flexible workflows, Linear unlocks your team’s full potential. It
							is the tool of choice for high-performance teams to build products
							better.
						</p>
					</div>
				</div>
			</main>
		</>
	);
};

export default Features;
