import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import styles from './index.module.scss';

const Features: NextPage = () => {
	return (
		<>
			<Head>
				<title>Features</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.svg" />
			</Head>

			<main className="main">
				<div className={styles.page_content}>
					<div className={styles.masthead}>
						<div className={styles.logo}>
							<Image src="icon.svg" width={64} height={64} alt="logo"></Image>
						</div>
						<span>Features</span>
						<h1>The new standard for modern software development</h1>
						<p>
							With its meticulous design, breathtaking speed and opinionated yet
							flexible workflows, Linear unlocks your team’s full potential. It
							is the tool of choice for high-performance teams to build products
							better.
						</p>
					</div>
					<hr />
					<div className={styles.feature}>
						<h1 className={styles.first}>Repository Management</h1>
						<p>
							Onara allows users to create, edit and delete repositories. We
							also provide you with the ability to customize access to
							repositories according to different levels of access rights.
						</p>
					</div>
					<hr />
					<div className={styles.feature}>
						<h1 className={styles.second}>Teamwork</h1>
						<p>
							Onara has functionality for collaborating on repositories. Onara
							also allows users to create teams, manage team memberships, and
							assign different levels of access to team members.
						</p>
					</div>
					<hr />
					<div className={styles.feature}>
						<h1 className={styles.third}>Voting</h1>
						<p>
							Onara has the functionality to vote for pull requests. Users can
							upvote or downvote the pull request, and the application can use
							this information to determine whether to commit changes to the
							repository.
						</p>
					</div>
				</div>
			</main>
		</>
	);
};

export default Features;
