import { GetStaticProps } from 'next';

import type { NextPage } from 'next';

import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import fs from 'fs/promises';
import path from 'path';

import matter from 'gray-matter';

import { MDXRemote } from 'next-mdx-remote';
import { serialize } from 'next-mdx-remote/serialize';

import IconWrapper from '@/components/IconWrapper';

import styles from './index.module.scss';

const components = {
	Image,
};

interface PostData {
	[key: string]: any;
}

interface Post {
	slug: string;
	frontMatter: PostData;
}

interface ChangelogPageProps {
	posts: Post[];
}

const Changelog: NextPage<ChangelogPageProps> = ({ posts }) => {
	return (
		<>
			<Head>
				<title>Changelog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.svg" />
			</Head>

			<div className={styles.page_content}>
				<main className="main">
					<div className={styles.masthead}>
						<div className={styles.masthead_content}>
							<h1 className={styles.title}>Changelog</h1>
							<div className={styles.subtitle}>
								New updates and improvements to Onara.
								<div className={styles.links}>
									<Link
										href=""
										onClick={() => alert('This button is not working yet')}
									>
										Subscribe to updates
										<IconWrapper width={14} height={14}>
											<path
												strokeLinecap="round"
												strokeLinejoin="round"
												d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25"
											/>
										</IconWrapper>
									</Link>
									<Link href="https://t.me/+wK4gxiduYBwxYzFi" target="_blank">
										Follow us on Telegram
										<IconWrapper width={14} height={14}>
											<path
												strokeLinecap="round"
												strokeLinejoin="round"
												d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25"
											/>
										</IconWrapper>
									</Link>
								</div>
							</div>
						</div>
					</div>
				</main>

				{posts.map((post) => {
					console.log(post);

					return (
						<div key={post.slug} className={styles.changelog}>
							<div className={styles.changelog_content}>
								<div className={styles.date}>
									<p>{post.frontMatter.releaseDate}</p>

									<p>
										{post.frontMatter.isToday ? (
											<span>(Today&apos;s log)</span>
										) : (
											<span>{`(${post.frontMatter.diffDays} days ago)`}</span>
										)}
									</p>
								</div>

								<div className={styles.details}>
									<MDXRemote
										{...post.frontMatter.content}
										components={components}
									/>
								</div>
							</div>
						</div>
					);
				})}
			</div>
		</>
	);
};

const getFormattedDate = (fileName: string) => {
	// Extract the date parts from the file name
	const [day, month, year] = fileName.split('.')[0].split('-');

	// Create a Date object from the extracted parts
	const date = new Date(`${month}-${day}-${year}`);
	console.log('date', date);

	const options: Intl.DateTimeFormatOptions = {
		day: 'numeric',
		month: 'long',
		year: 'numeric',
	};

	const formattedDate = date.toLocaleDateString('en-US', options);
	const today = new Date();
	const isToday = today.toLocaleDateString('en-US', options) === formattedDate;

	const diffTime = Math.abs(today.getTime() - date.getTime());
	let diffDays = Math.ceil(
		(diffTime - today.getTimezoneOffset() * 60 * 1000) / (1000 * 60 * 60 * 24)
	);

	if (diffDays > 0) {
		diffDays -= today.getDate() > date.getDate() ? 1 : 0;
	}

	if (diffDays < 1) {
		if (isToday) {
			return { formattedDate, isToday: true, diffDays };
		}
	}

	return { formattedDate, isToday: false, diffDays };
};

const getPosts = async (): Promise<Post[]> => {
	// Get the path to the directory containing the MDX files
	const mdxFilesDirectory = path.join(process.cwd(), 'posts/changelog');
	const mdxFiles = await fs.readdir(mdxFilesDirectory);

	const posts = await Promise.all(
		mdxFiles.map(async (file) => {
			const slug = file.replace(/\.mdx?$/, '');
			const fullPath = path.join(mdxFilesDirectory, file);
			const fileContents = await fs.readFile(fullPath, 'utf8');
			const { data, content } = matter(fileContents);

			const mdxSource = await serialize(content, {
				scope: data,
			});

			const { formattedDate, isToday, diffDays } = getFormattedDate(slug);

			return {
				slug,
				frontMatter: {
					...data,
					content: mdxSource,
					releaseDate: formattedDate,
					isToday,
					diffDays,
				},
			};
		})
	);

	const sortedPosts = posts.sort((a, b) => {
		const dateA = new Date(a.frontMatter.releaseDate);
		const dateB = new Date(b.frontMatter.releaseDate);

		if (dateA > dateB) return -1;
		if (dateA < dateB) return 1;
		return 0;
	});

	return sortedPosts;
};

export const getStaticProps: GetStaticProps<ChangelogPageProps> = async () => {
	const posts = await getPosts();

	return {
		props: {
			posts,
		},
	};
};

export default Changelog;
