'use client';

import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import styles from './index.module.scss';

const Custom404: NextPage = () => {
	return (
		<>
			<Head>
				<title>Page not found · Onara</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.svg" />
			</Head>
			<div className={styles.error_page}>
				<h1>404 - Page Not Found</h1>
				<p>The page you are looking for does not exist.</p>

				<Link href="/">Homepage</Link>
			</div>
		</>
	);
};

export default Custom404;
