import Head from 'next/head';
import styles from './index.module.scss';

import { useSession } from 'next-auth/react';

const User = () => {
	const { data } = useSession();

	return (
		<div className="main">
			<Head>
				<title>Onara</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.svg" />
			</Head>

			<h1>{data?.user?.name}</h1>
		</div>
	);
};

export default User;
